---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: 12-example
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::047339594014:role/production-prod-cluster-myapp-secrets
